repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: check-yaml
    -   id: check-json
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-added-large-files
        args: ['--maxkb=3000']
    -   id: debug-statements
    -   id: check-symlinks
    -   id: check-merge-conflict
-   repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
    -   id: black
-   repo: https://github.com/asottile/reorder_python_imports
    rev: v3.1.0
    hooks:
    -   id: reorder-python-imports
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
    -   id: flake8
        args:
        -   "--max-line-length=120"
        -   "--ignore=E128, E203, W503"
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.961
    hooks:
    -   id: mypy
        additional_dependencies: ['types-PyYAML']
-   repo: https://github.com/pre-commit/mirrors-clang-format
    rev: 'v14.0.6'  # Use the sha / tag you want to point at
    hooks:
    -   id: clang-format
